- INSTALL.md
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/1
> Improve installation instructions for fresh conda

- README.md
This should fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/18 and https://github.com/facebookresearch/maskrcnn-benchmark/issues/33
> Improve single-GPU explanation in the README

- README.md
- TROUBLESHOOTING.md
Fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/25 and https://github.com/facebookresearch/maskrcnn-benchmark/issues/30
Thanks @gf19880710 for the step-by-step solution!
> Add TROUBLESHOOTING section

- INSTALL.md
- TROUBLESHOOTING.md
Fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/21
> Add note about GCC < 4.9

- ABSTRACTIONS.md
Replace BoxList argument size with image_size.
> Addresses #68 - Update ABSTRACTIONS.md

- maskrcnn_benchmark/structures/bounding_box.py
A quick fix for #96 in area computation. The clipping is somehow more tricky so I can't fix it on github page.
> quick fix for area

- demo/predictor.py
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/185
> Fix demo after PostProcess mask

- README.md
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/189
> Add reference bibtex for citations

- docker/Dockerfile
@keineahnung2345 your approach was indeed better, the conda installation of opencv is not compiled against all of opencv's functionalities.
This PR fixes the opencv installation
> fix opencv installation in dockerfile

- demo/README.md
> README instructions for demo with docker

- maskrcnn_benchmark/modeling/rpn/anchor_generator.py
Nothing significant. Removed a line of unused code left in the file.
> remove unused code

- maskrcnn_benchmark/utils/comm.py
@fmassa I believe this should handle the distributed training check as you suggested.
> Added distributed training check

- maskrcnn_benchmark/config/paths_catalog.py
Address some comments from @zimenglan-sysu-512 in https://github.com/facebookresearch/maskrcnn-benchmark/commit/e0a525a0139baf7086117b7ed3fd318a4878d71c
> Clean paths_catalog for keypoints

- INSTALL.md
the env variable is misused in the current version
> clear up MASKRCNN_BENCHMARK_INSTALL_DIR

- maskrcnn_benchmark/data/README.md
Remove note after merging #457
> remove note for detectron dependency

- maskrcnn_benchmark/engine/inference.py
Fixing #280 in another place, that was previously missed.
> Using existing get_world_size to prevent AttributeError

- maskrcnn_benchmark/structures/image_list.py
Useful for some examples with the webcam
> Update ImageList to work with 3d tensors

- README.md
- maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu
- maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu
- maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu
- maskrcnn_benchmark/csrc/cuda/nms.cu
Reverts facebookresearch/maskrcnn-benchmark#537
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/607
> Revert "Support for running on arbitrary CUDA device."

- docker/Dockerfile
add tqdm in line32 : RUN pip install ninja yacs cython matplotlib opencv-python tqdm
> Add tqdm package in Dockerfile

- INSTALL.md
- README.md
- maskrcnn_benchmark/utils/model_zoo.py
This PR addresses some _nits_:
- Finishes #695 by adding a comment on the README;
- Removes the "optional" message that I should've removed when I submitted #694 but I did not notice before;
- Addresses https://github.com/thomasshupeng/maskrcnn-benchmark/pull/1#issuecomment-485093200, by adding `ImportError` to a generic `except` and swap the order (first try the new API, then fallback to the old one as you suggested in https://github.com/facebookresearch/maskrcnn-benchmark/pull/673#pullrequestreview-226527910)
> Update documentation and remove a generic except

- maskrcnn_benchmark/utils/comm.py
change torch.IntTensor to torch.LongTensor in all_gather  for storing large tensor numel.
> change torch.IntTensor to torch.LongTensor in all_gather 

- INSTALL.md
- maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu
Updated SigmoidFocalLoss.cu (converted to long ) as in [Pull 409 ](https://github.com/facebookresearch/maskrcnn-benchmark/pull/409)  
and add a step by step  windows installation instruction
> Windows10 installation fixes ver2

- maskrcnn_benchmark/structures/segmentation_mask.py
Fix for PR #777 with efficient implementation of the functionality.
Thanks @krumo for proposing the feature!
Hopefully this motivates a PR for #169
> support empty BinaryMaskList initialization

- maskrcnn_benchmark/engine/inference.py
now can inference on cpu by setting MODEL.DEVICE cpu
> enable inference on cpu

- maskrcnn_benchmark/modeling/backbone/resnet.py
clean up resnet code
related #797
> out0 to out in resnet

- docker/docker-jupyter/Dockerfile
From https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md:
1. additionally install tqdm, cudatoolkit, apex
2. add FORCE_CUDA argument
Note that the argument CUDA is re-declared, this is done so that its value can be reused, following the instruction [here](https://github.com/moby/moby/issues/37622#issuecomment-412101935).
> update dockerfile according to the new INSTALL.md

- tools/test_net.py
Regarding the backward-compatibility in this PR #874.
> allow test for checkpoint from cfg.MODEL.WEIGHT

- maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py
- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
- maskrcnn_benchmark/modeling/rpn/loss.py
Fix minor typos in roi_head and a mistake comment of args in rpn loss.
> fix minor typos

- README.md
cc @rbgirshick @ppwwyyxx @botcs @soumith
> Redirect users to Detectron2

- README.md
add the MULAN project in readme.MD, "Projects using maskrcnn-benchmark"
> Update README.md by adding a project using maskrcnn-benchmark
