- INSTALL.md
It is simpler and requires less effort (i.e. no auth) compared to SSH
> Access repos via https in INSTALL.md

- .gitignore
JupyterLab (not sure about Jupyter Notebook) automatically create checkpoints folder when run any .ipynb notebook.
It makes sense to ignore them.
> Update gitignore ipynb_checkpoints

- maskrcnn_benchmark/utils/comm.py
- maskrcnn_benchmark/utils/logger.py
- tools/test_net.py
- tools/train_net.py
Current implementation is subject to [PyTorch issue 12042](https://github.com/pytorch/pytorch/issues/12042) due to using `--local-rank` to detect the master process when training on more than 1 nodes.
This fix uses `distributed.get_rank()` to detect the master process and should therefore allow training with multiple nodes on shared file systems.
> Use dist.get_rank() instead of local_rank to detect master process

- maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/59
Thanks @godimarcovr for catching the bug!
> Fix weight init in FastRCNNPredictor

- ABSTRACTIONS.md
Replace baseline with benchmark
> Addresses #68 - Update ABSTRACTIONS.md

- INSTALL.md
- docker/Dockerfile
Added Dockerfile to build with CUDA
Example build script with defaults (`CUDA_VERSION=9.0`, `CUDNN_VERSION=7`):
```bash
nvidia-docker build -t maskrcnn-benchmark docker/ 
```
Example build script with other CUDA and CUDNN versions:
```bash
nvidia-docker build -t --build-arg CUDA_VERSION=9.2 --build-arg CUDNN_VERSION=7 maskrcnn-benchmark docker/ 
```
> adds Dockerfile

- maskrcnn_benchmark/config/defaults.py
- maskrcnn_benchmark/modeling/backbone/backbone.py
- maskrcnn_benchmark/modeling/backbone/resnet.py
- maskrcnn_benchmark/modeling/registry.py
- maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_feature_extractors.py
- maskrcnn_benchmark/modeling/rpn/rpn.py
- maskrcnn_benchmark/utils/c2_model_loading.py
- maskrcnn_benchmark/utils/registry.py
Adding a basic registration module for backbone and roi & rpn heads. For adding customized building blocks, one can write new functions/modules with `register` decorators in separate files.
> Add registry for model builder functions

- INSTALL.md
- docker/Dockerfile
The argument names where being overridden by the CUDA image env variables, resulting in a failure in the NCCL2 installation.
This fixes the issue
> Docker hotfix

- docker/Dockerfile
`RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections`
fixes
> debconf: unable to initialize frontend: Dialog
> debconf: (TERM is not set, so the dialog frontend is not usable.)
> debconf: falling back to frontend: Readline
> debconf: unable to initialize frontend: Readline
> debconf: (This frontend requires a controlling tty.)
> debconf: falling back to frontend: Teletype
> dpkg-preconfigure: unable to re-open stdin: 
`RUN apt-get update -y && apt-get install -y apt-utils`
fixes
> debconf: delaying package configuration, since apt-utils is not installed
> fix some minor issues in dockerfile

- maskrcnn_benchmark/structures/bounding_box.py
- tools/test_net.py
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/92
Also fixes some linter issues (we use `"` instead of `'` for strings).
> Pass OUTPUT_DIR to Checkpointer during inference

- maskrcnn_benchmark/config/defaults.py
- maskrcnn_benchmark/engine/inference.py
- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
This is a copy of https://github.com/facebookresearch/maskrcnn-benchmark/pull/124 after rebase and with a very simple warning fix.
Thanks a lot @hadim!
> Add an option to postprocess masks during inference

- docker/Dockerfile
cv2 is used by predictor.py, so it's required
> add opencv support to Dockerfile

- INSTALL.md
When using the docker build command in INSTALL.md:
`nvidia-docker build -t --build-arg CUDA=9.2 --build-arg CUDNN=7 maskrcnn-benchmark docker/ `
The following error occurs:
```
invalid argument "--build-arg" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```
This happens because the order of the command is wrong. I changed the order of the command so that the error doesnt occur and the docker image can be built.
> changed the order of the docker build command

- maskrcnn_benchmark/engine/trainer.py
`iteration` will be not declared if we load a fully trained checkpoint.
> fix crash caused by saving model when staring from max iter

- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
In maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
change line 125-126 to
w = int(box[2] - box[0] + TO_REMOVE)
h = int(box[3] - box[1] + TO_REMOVE)
> fix integer bug (#239)

- maskrcnn_benchmark/modeling/matcher.py
This should help catch problems similar to the one in https://github.com/facebookresearch/maskrcnn-benchmark/issues/31
> Raise error if no GT or proposals available during training

- maskrcnn_benchmark/engine/inference.py
Maybe this is the behavior that the authors would like to see, I guess.
> fix tqdm usage

- maskrcnn_benchmark/csrc/cuda/nms.cu
Here it is indexing a cuda tensor with CPU indices. It used to work, but 
after https://github.com/pytorch/pytorch/commit/006505bb8f9dcf0f38b32518308d071c8a1ccec6 it results in memory corruption.
> Fix indexing error in nms kernel

- demo/predictor.py
fix https://github.com/facebookresearch/maskrcnn-benchmark/issues/266
> fix error when running with --show-mask-heatmaps

- maskrcnn_benchmark/utils/metric_logger.py
- tests/test_metric_logger.py
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/278
> Fix error in MetricLogger for non-existing attributes

- README.md
> add finetune from detectron guide

- maskrcnn_benchmark/solver/lr_scheduler.py
PR for the [issue warmup linear problem](https://github.com/facebookresearch/maskrcnn-benchmark/issues/335) to the Python 2-3 compatibility issue.
> a Python 2-3 compatibility issue in lr_scheduler.py

- maskrcnn_benchmark/modeling/rpn/loss.py
Reverts facebookresearch/maskrcnn-benchmark#359
Fixes https://github.com/facebookresearch/maskrcnn-benchmark/issues/363
There should have been a change in the `layers/smooth_l1_loss.py` as well. Reverting this change.
> Revert "swich to new pytorch api"

- demo/predictor.py
- maskrcnn_benchmark/utils/cv2_util.py
- tools/cityscapes/instances2dict_with_polygons.py
Small PR to fix the version compatibility problem with `cv2.findContours` returning either 2 or 3 values depending on the cv2 version.
I replaced all occurrences of `cv2.findContours` with the helper.
I put the code in `utils/` dir. Seemed like the best place for it, but please advise.
I tested locally by installing my branch locally using:
```
pip install -U git+https://github.com/aaronlelevier/maskrcnn-benchmark.git@train
```
Then ran the `demo/Mask_R-CNN_demo.ipynb ` and it worked as expected, even though my `cv2` version is `opencv-python==4.0.0.21`, so this is now compatible with either version.
fixes #336 
#339 also referenced this error but the issue is already closed
> Add helper function "cv2_utils.findContours" to maintain version compatibility between versions 3 and 4

- README.md
- maskrcnn_benchmark/config/paths_catalog.py
Add the COCO_2017 link. In 2017, COCO changed the train/val splits based the research community feedback.
`COCO_2017_train` = `COCO_2014_train` + `valminusminival`
`COCO_2017_val` = `minival`
This just makes the setting of COCO simpler and does not need to download the annotations outside the COCO website. It will also be useful for combing the stuff annotation in the future.
> Add COCO_2017 in paths_catalog.py

- maskrcnn_benchmark/engine/inference.py
- maskrcnn_benchmark/utils/comm.py
> use all_gather to gather results from all gpus

- maskrcnn_benchmark/utils/comm.py
- tools/test_net.py
- tools/train_net.py
Use `torch.distributed.barrier` instead of `torch.distributed.broadcast` in `synchronize` function. Discussed in issue #172 .
> use dist.barrier to synchronize

- maskrcnn_benchmark/data/datasets/coco.py
This PR addresses the cases in which **all** bounding boxes of an image have `width` or `height` less than or equal to 1. In these cases, these training images would have no bounding boxes (they are filtered on the `clip_to_image(...)`  later), which would throw an exception (#37). The problem was discussed in #31 ([here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/31#issuecomment-458988209)).
> Remove images in which all bboxes have width or height <= 1

- maskrcnn_benchmark/config/defaults.py
Since IMS_PER_BATCH is global, it shouldn't be multiplied with the # of GPUs.
> FIxed comment for # of RoIs per minibatch

- maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py
I get the following error when execute `tools/train_net.py`:
```
Traceback (most recent call last):
File "tools/train_net.py", line 172, in <module>
main()
File "tools/train_net.py", line 165, in main
model = train(cfg, args.local_rank, args.distributed)
File "tools/train_net.py", line 30, in train
model = build_detection_model(cfg)
File "/content/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 10, in build_detection_model
return meta_arch(cfg)
File "/content/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 31, in __init__
self.roi_heads = build_roi_heads(cfg)
File "/content/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 46, in build_roi_heads
roi_heads.append(("box", build_roi_box_head(cfg)))
File …
```
> Fix `NameError: name 'cfg' is not defined` in roi_box_predictors.py

- maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu
- maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu
This PR fixes the build-errors on Windows caused by invalid types when calling THCC……eilDiv. Adding type-cast to (long) to first parameter to fix the errors.
Resolved issue: #254
Simpler alternative to: #271
> Fixing build-errors on Windows

- maskrcnn_benchmark/modeling/registry.py
- maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py
- maskrcnn_benchmark/structures/bounding_box.py
- maskrcnn_benchmark/utils/logger.py
- Add a registry `ROI_BOX_PREDICTOR`
- Use the registry in `roi_box_predictors.py`, replacing the local factory
- Minor changes in `structures/bounding_box.py`: when copying a box with fields, check if the field exists
- Minor changes in `logger.py`: make filename a optional argument with default value of `"log.txt"`
> Registry for RoI Box Predictors

- maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py
I was writing a script and saw some of these TODOs on `coco_eval.py` and I agree that using `get_img_info(...)` should be preferred. As they were straightforward to implement, here we are. I kept the same "style" used on [voc_eval.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/evaluation/voc/voc_eval.py#L18-L22). I performed an evaluation before and after the changes and I had no problems, as expected.
Although the TODOs seemed to be related only with the `width` and `height`, if we could assume that `dataset` is an instance of `COCODataset`, we could also change `original_id` to `img_info["id"]`. I was not sure about this assumption, because there are `assert`s in the beginning of these functions that are commented out.
> Replace with get_img_info on coco_eval

- maskrcnn_benchmark/data/samplers/distributed.py
Issue #437 
Replaced hardcoded value of shuffle with `self.shuffle = shuffle`
>  Replaced hard coding for shuffle variable

- maskrcnn_benchmark/config/paths_catalog.py
fix inconsistent keypoint dataset paths in paths_catalog.py
> fix keypoint dataset path error in paths_catalog.py

- maskrcnn_benchmark/data/README.md
A few addition:
I added the top level directory `cityscapes` since the `tools/cityscapes/convert_cityscapes_to_coco.py` script has the directory structure `gtFine_trainvaltest/gtFine` hardcoded into it which is fine but was not clear at first.
Also added a **Note** to warn people to install detectron as well, since the script uses `detectron.utils.boxes` and `detectron.utils.segm` modules which has further dependencies in the detectron lib.
> clarifying directory structure and fixing typo

- INSTALL.md
The previous instruction examples assumed that the directory `~/github` existed, and did not include any check to create it if the directory did not exist. I updated to install in whatever directory the user is current in. 
I also updated to make it clear how the CUDA version is specified, and fixed a typo in activating the conda env.
> Update install example to avoid directory assumptions

- INSTALL.md
Finishing the clean up in https://github.com/facebookresearch/maskrcnn-benchmark/pull/455, unsetting the proper variable. 
In general, thanks for making this so easy to install! I'd run into all kinds of versioning issues (version of Ubuntu not playing nicely with versions of CUDA/pytorch/libraries) trying to install other libraries implementing these algorithms. I'm super impressed by the quality of support, and the easy install, for this library.
> unsets proper variable

- tools/cityscapes/convert_cityscapes_to_coco.py
Contribution to CityScapes -> COCO converter, following up on #447 .
I have looked into the boxes.py to swap [these lines](https://github.com/facebookresearch/Detectron/blob/8170b25b425967f8f1c7d715bea3c5b8d9536cd8/detectron/utils/boxes.py#L51L52):
```
import detectron.utils.cython_bbox as cython_bbox
import detectron.utils.cython_nms as cython_nms
```
```
from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
from maskrcnn_benchmark.structures.boxlist_ops import boxlist_nms
```
However some functions are missing from the `boxlist_ops` like the [`soft_nms`](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/cython_nms.pyx#L98L203) .
So I just tried to modify the `maskrcnn-benchmark/tools/cityscapes/convert_cityscapes_to_coco.py` script.
Here we have …
>  Remove Detectron dependency

- tools/train_net.py
I'm using pycharm to debug the code on a remote server, the remote debugging seems to be performed by pytest and it pops errors like:
> train_net.py E
> test setup failed
> file /tmp/pycharm_project_269/tools/train_net.py, line 79
>   def test(cfg, model, distributed):
> E       fixture 'cfg' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
it seems the function name ‘test()’ has come conflict with pytest, so it may be better use another name.
> change test() to run_test()

- INSTALL.md
-> don't need the pytorch nightly
-> not enforcing cuda 9.0
-> using torchvision
-> reorder so the pip install -r requirement.txt comes after clone and not before
> fix INSTALL.md

- maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp
- maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp
- maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu
- maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu
- maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu
@fmassa This fixes the dispatch breakage introduced by https://github.com/pytorch/pytorch/commit/3aeb78079bcd68282fe9117088e138b77318e288.
Closes https://github.com/pytorch/pytorch/issues/17861
> Fix dispatch breakage

- INSTALL.md
Fixes problems introduced in https://github.com/facebookresearch/maskrcnn-benchmark/pull/510
Also explicitly mention that since https://github.com/facebookresearch/maskrcnn-benchmark/pull/555 `maskrcnn-benchmark` will not work with PyTorch 1.0 nor 1.0.1, but only with a recent enough nightly
> Fix installation instructions and pin PyTorch to a nightly

- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
In PR #473 @fmassa [pointed out](https://github.com/facebookresearch/maskrcnn-benchmark/pull/473#issuecomment-468231101) that `torch.nn.functional.interpolate` does not handle well empty tensors, and proposed using `maskrcnn_benchmark.layers.misc.interpolate` instead.
This modification helps to avoid such errors when using the `Masker`
> use internal interpolate implementation

- README.md
Documents the places where the python code needs to be changed in order to add a custom dataset.
Proposing this to reduce the volume of issues until there is a more extensive tutorial as started in https://github.com/facebookresearch/maskrcnn-benchmark/issues/521.
> README - add your own dataset

- README.md
- maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu
- maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu
- maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.cu
- maskrcnn_benchmark/csrc/cuda/nms.cu
The current version could not normally run someone CUDA device (e.g. **cuda:1**).
The program will show such errors if we only add a extra flag `MODEL.DEVICE cuda:1`
`
2019-03-06 19:41:24,027 maskrcnn_benchmark.trainer INFO: Start training
THCudaCheck FAIL file=/home/dl/KJ/dl/core/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu line=103 error=77 : an illegal memory access was encountered
`
The issue is that the current executable device (on CUDA) is device:0, while the memory data of tensors (boxes, etc.) is allocated on device:1. Therefore, we need temporary switch device 0 to 1.
After fixed the issue:
`2019-03-06 19:51:47,698 maskrcnn_benchmark.trainer INFO: Start training
2019-03-06 19:51:55,449 maskrcnn_benchmark.trainer INFO: eta: 3 days, 5:29:26  iter: 20  loss: 1.8457 …
> Support for running on arbitrary CUDA device.

- docker/Dockerfile
Fixes an issue where conda would install CUDA version 10.0 by default as opposed to the one specified in the build arg
> Fixes conda CUDA version in Dockerfile

- INSTALL.md
- demo/README.md
- docker/Dockerfile
- setup.py
cf [#167](https://github.com/facebookresearch/maskrcnn-benchmark/issues/167) 
this seems to be the best workaround
> add the option to use a `FORCE_CUDA` to force cuda installation on docker

- docker/Dockerfile
Fix a bug.
Romove the echo command in line 36: RUN conda install pytorch-nightly cudatoolkit=${CUDA} -c pytorch 
To enable conda installation of pytorch-nightly.
> Fix a bug in Docker file

- README.md
FCOS is a new object detection framework. The framework totally eliminates pre-defined anchor boxes and achieves better performance than its anchor-based counterpart RetinaNet with the advantage of being much simpler.
Our FCOS implementation is based on your work maskrcnn-benchmark. Therefore we want to add it into the list of projects using maskrcnn-benchmark. Hope you can merge our pull request. Thank you very much.
> Add FCOS into projects using maskrcnn-benchmark.

- maskrcnn_benchmark/structures/segmentation_mask.py
https://gist.github.com/botcs/a59f3f59e22e5df93e3e5e4f86718af3
> Add RLE support

- maskrcnn_benchmark/structures/segmentation_mask.py
in compressed RLE format (from pycocotools), height comes first in "size".
> [Masks] image size in RLE assert

- INSTALL.md
- docker/Dockerfile
- maskrcnn_benchmark/config/defaults.py
- maskrcnn_benchmark/engine/trainer.py
- maskrcnn_benchmark/layers/batch_norm.py
- maskrcnn_benchmark/layers/nms.py
- maskrcnn_benchmark/layers/roi_align.py
- maskrcnn_benchmark/layers/roi_pool.py
- maskrcnn_benchmark/modeling/poolers.py
- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
- tools/test_net.py
- tools/train_net.py
This PR adds initial mixed-precision training support via [apex.amp](https://github.com/NVIDIA/apex/tree/master/apex/amp).
Mixed-precision is controlled with the `SOLVER.MIXED_PRECISION` config argument.
Along with `apex.amp` support, I've moved `DistributedDataParallel` to `apex.DistributedDataParallel` as this is what we've been using to good effect over the last few months.
Please note that this does add the `apex` package as a requirement.
> Initial mixed-precision training

- maskrcnn_benchmark/config/defaults.py
- maskrcnn_benchmark/modeling/rpn/inference.py
This PR complements https://github.com/facebookresearch/maskrcnn-benchmark/pull/676, adding the `MODEL.RPN.FPN_POST_NMS_PER_BATCH` switch:
- `True` (default): the code behaves AS IS, to keep it consistent with Detectron;
- `False`: POST_NMS is then applied per image, as "it should be":
https://github.com/facebookresearch/maskrcnn-benchmark/blob/08fcf12f4b8ef16e5903f859a62307950b886f89/maskrcnn_benchmark/modeling/rpn/inference.py#L157-L158
I was wondering if I should add a comment on the README; something like this (changes in bold):
> Furthermore, we set `MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN 2000` as the proposals are selected for per the batch rather than per image **in the default training**. The value is calculated by 1000 x images-per-gpu. Here we have 2 images per GPU, therefore we set …
> Add a switch for POST_NMS per batch/image during training

- INSTALL.md
Minor stuff on the INSTALL instructions:
1. After b4d546577850b156939067794f155526e262ee61, OpenCV is now required. We can either perform a check (maybe the user is using only Faster R-CNN) or just add `opencv-python` in the INSTALL instructions. This PR goes with the second option;
2. This PR also fixes the `~github` used during the `apex` install. The convention was adopted after the beginning of the `mixed-precision` PR.
If you do a fresh install and try to run the train command on the README, you get this error:
```bash
Traceback (most recent call last):
File "tools/train_net.py", line 15, in <module>
from maskrcnn_benchmark.data import make_data_loader
File "/home/berriel/projects/maskrcnn-benchmark-fork/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
from .build import …
```
> Add OpenCV in the INSTALL instructions

- README.md
Update documentation for testing and calculating mAP for each class.
> Evaluation details

- maskrcnn_benchmark/config/defaults.py
Noticed the names in the comment do not correspond to any actual params, fixing to refer to an actual one.
> Quickfix for outdated param names

- maskrcnn_benchmark/data/datasets/coco.py
Resolves the naming clash with torchvision `CocoDetection` class introduced by torchvision commit [#872](https://github.com/pytorch/vision/commit/0c36735d2ca6dfbb56a95da444b708b7c535a2c8).
For a detailed bug description, please see #738.
> Renames the `transforms` attribute of COCODataset

- maskrcnn_benchmark/data/datasets/coco.py
Hi,
As reported in [this](https://github.com/facebookresearch/maskrcnn-benchmark/issues/809) issue, when there is no `segmentation` field in the json file (which I believe will be quite common in practice, since most people would like to use this codebase in the bbox detection task), there will be a error of `index out of range` in the `boxlist` indexing operations. I feel maybe this modification would allow to get rid of this error by not adding the filed of `mask` to the `bboxlist` object.
I am not sure whether this modification is in consistent with  the designing spirit of this repo. If it is not proper to implement this modification, please let me know and I will delete this pr so that we can discuss another place where I feel maybe a little modification will make it better :)
> modify senario where dataset has no mask provided

- maskrcnn_benchmark/structures/boxlist_ops.py
1. In nms function, set max_proposals to min(max_proposals, len(keep)) to protect against over indexing.
2. In iou function, convert boxlist to xyxy mode explicitly to prevent unwarned malfunction.
> some protection code in bounding box operations

- demo/predictor.py
The result may be affected  when   the implementation of resize function in inference time  and training time is inconsistent,so I changed the code in inference time to keep them same.
> keep the resize function the same in test time the same with training time

- .gitignore
- maskrcnn_benchmark/data/build.py
The assert message is split up in 2 strings:
```python
"SOLVER.IMS_PER_BATCH ({}) must be divisible by the number "
"of GPUs ({}) used.".format(images_per_batch, num_gpus)
```
str.format() is only applied to the second string, which produces an incorrect message, where the first placeholder is not substituted and the second is incorrectly substituted.
Example: `SOLVER.IMS_PER_BATCH ({}) must be divisible by the number of GPUs (32) used.`
> minor fix: incorrect assert string message formatting

- README.md
Highlight the model support for mixed precision training and add instruction to enable it on README
> Add mixed precision training instruction

- demo/shapes_dataset_demo.ipynb
Fix typo, highlight words in python language, add hyperlink
> Fix typo for shapes_dataset_demo.ipynb

- maskrcnn_benchmark/utils/checkpoint.py
- tools/test_net.py
> allow test for any checkpoint

- demo/shapes_pruning.ipynb
I was experimenting with pruning of object detection algorithms and was able to get some good results using the detectors in this repo. I though I'd share a popular technique for pruning via a demo here.
The algorithm used for pruning is from the "To Prune or not to Prune" [paper](https://arxiv.org/abs/1710.01878) that is incidentally used by the Tensorflow Model Optimisation Toolkit to perform pruning.
I was able to bring about a sparsity of 70% with almost no loss in mAP using this technique. I suspect getting upto a 90% sparsity is also possible with more training. Here I have only applied pruning masks to the convolutional filters (more specifically around 100 conv layers were pruned).
This branch of research is particularly exciting as one can (theoretically) get a lot of speed ups …
> Unstructured Pruning Demo

- maskrcnn_benchmark/data/datasets/__init__.py
- maskrcnn_benchmark/data/datasets/abstract.py
- maskrcnn_benchmark/structures/segmentation_mask.py
In this PR a generic dataset definition is introduced: AbstractDataset which contains the bare minimum to bootstrap a training with custom datasets. This class should be derived for generic support of training and evaluation tools.
```
Serves as a common interface to reduce boilerplate and help dataset
customization
A generic Dataset for the maskrcnn_benchmark must have the following
non-trivial fields / methods implemented:
CLASSES - list/tuple:
A list of strings representing the classes. It must have
"__background__" as its 0th element for correct id mapping.
__getitem__ - function(idx):
This has to return three things: img, target, idx.
img is the input image, which has to be load as a PIL Image object
implementing the target requires the most effort, since it must have
multiple …
```
> Add Abstract dataset definition

- maskrcnn_benchmark/layers/sigmoid_focal_loss.py
Fixes #1013
It appeared in this commit https://github.com/chengyangfu/maskrcnn-benchmark/commit/26c707e798d830bbf048380eaf78adad60873c8a#diff-10a14e932c16f4c03e825ff3f60720f0 
This is the only place of initialization of alpha and gamma.  https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/rpn/retinanet/loss.py#L94
If I understand correctly they are supposed to be only as floats according to configs
```
cfg.MODEL.RETINANET.LOSS_GAMMA,
cfg.MODEL.RETINANET.LOSS_ALPHA
```
- [unittests OK] 
I tried to run this for `configs/retinanet/retinanet_R-50-FPN_P5_1x.yaml`
- [train_net.py, test_net.py with GPU]
- [test_net.py with CPU]
> gamma, alpha are supposed to be floats, delete lines with [0] subscripts   #1013

- INSTALL.md
creating the conda env does not come with a local version of pip, therefore in line 27 it would be quite non-deterministic where the installed lib would end up, possibly causing collisions with different versions of this or other repos
> install local pip with conda

- maskrcnn_benchmark/structures/segmentation_mask.py
Mask annotation dict can have 2 states
1. compressed RLE that was handled by code.
2. uncompressed RLE, like coco annotation
{'counts': [6, 1, 40, 4, 5, 4, 5, 4, 21], 'size': [9, 10]}
this state was not included by code condition.
> Add uncompressed rle condition in Binarymask

- maskrcnn_benchmark/modeling/rpn/retinanet/inference.py
Remove redundant reshape in line `77` 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/rpn/retinanet/inference.py#L76-L77
Because `permute_and_flatten` makes this reshape already
https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/modeling/rpn/utils.py#L10-L14
> remove redundant reshape of box_regression

- maskrcnn_benchmark/engine/trainer.py
According to the docs: https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.StepLR, now we need to call `scheduler.step()` after `optimizer.step()`. Breaking change PR: https://github.com/pytorch/pytorch/pull/7889
Currently, we just miss the first lr scheduler value which is not that critical.
> Update lr scheduling to pytorch 1.1.0

- demo/predictor.py
- maskrcnn_benchmark/modeling/balanced_positive_negative_sampler.py
- maskrcnn_benchmark/modeling/roi_heads/keypoint_head/loss.py
- maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
- maskrcnn_benchmark/modeling/rpn/anchor_generator.py
- maskrcnn_benchmark/modeling/rpn/inference.py
- maskrcnn_benchmark/structures/segmentation_mask.py
Indexing with dtype torch.uint8 is deprecated in pytorch 1.2.0. Current version generates lots of warnings like "/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead." 
In this PR, dtype torch.uint8 is replaced with torch.bool for indexing in compliance with pytorch 1.2.0.
> replacing dtype torch.uint8 with torch.bool for indexing in pytorch 1.2.0

- maskrcnn_benchmark/data/datasets/evaluation/__init__.py
- maskrcnn_benchmark/data/datasets/evaluation/cityscapes/__init__.py
- maskrcnn_benchmark/data/datasets/evaluation/cityscapes/cityscapes_eval.py
- maskrcnn_benchmark/data/datasets/evaluation/cityscapes/eval_instances.py
Currently VOC and COCO evaluations are present.
Reusing codebase from [CityscapesScripts](https://github.com/mcordts/cityscapesScripts/) this PR adds a native evaluation tool that is designed to work with all datasets derived from `AbstractDataset`
It aims for minimal modifications to the original code, for evaluation details please refer to it.
The output is returned in identical format (JSON), with the colored AP scores as well:
[TODO]: This tool can be verified by evaluating the `maskrcnn-benchmark` outputs with the original codes, this remains to be done
> Add native CityScapes evaluation tool

- maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py
- maskrcnn_benchmark/data/datasets/evaluation/coco/abs_to_coco.py
- maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval_wrapper.py
Using the standard `maskrcnn_benchmark/data/datasets/evaluation/coco/` tools, this PR introduces a wrapper that works with any derived class of the `AbstractDataset` and translates them into COCO annotation format ([details here](http://cocodataset.org/#format-data)). 
To unit-test this functionality the following measurement was carried out:
1. Derive a custom dataset `AbstractCOCO` from `AbstractDataset` 
2. wrap the original `COCODataset` inside `AbstractCOCO`. 
3. Evaluate `e2e_mask_rcnn_R_50_FPN_1x` and `e2e_mask_rcnn_R_50_FPN_1x`  with each dataset
5. Use the extended COCO evaluation tool and compare the results with the original tool.
4. **Results are non identical** because AbstractCOCO computes area by counting the nonzero entries of the binary masks, while in COCO annotations …
> Extend COCO evaluation for AbstractDataset 

- maskrcnn_benchmark/engine/inference.py
- tools/test_net.py
- tools/train_net.py
In `compute_on_dataset()` the default cfg object is used instead of the actual experiment configuration.
> bugfix: use correct config for tta and device handling during inference

- maskrcnn_benchmark/config/defaults.py
- maskrcnn_benchmark/data/transforms/build.py
Simple change to make it more consistent.
It was already there, but `#` :(
> Move horizontal flip probability to config

- README.md
Thanks for your excellent work! @fmassa 
Based on this repository, we research on the object detectors without sampling heuristics (e.g., Focal Loss, GHM, Undersampling).
The paper (https://arxiv.org/abs/1909.04868) and code (https://github.com/ChenJoya/sampling-free) have been released. Thank you again for maskrcnn-benchmark. It is a really simple, efficient, high performance object detection benchmark.
> Update README.md by adding a project using maskrcnn-benchmark
